Run test_iostream directly in PowerShell to let it use the nowide streambufs
This only happens when stdout/stdin is not redirected so also assert that

diff --git a/.github/workflows/ci_tests.yml b/.github/workflows/ci_tests.yml
--- a/.github/workflows/ci_tests.yml
+++ b/.github/workflows/ci_tests.yml
@@ -82,6 +82,7 @@ jobs:
       run: cmake .. -DBoost_DEBUG=ON -DCMAKE_BUILD_TYPE=${{matrix.buildType}} -DBUILD_SHARED_LIBS=${{matrix.shared_lib}} -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/../install -G "${{matrix.generator}}" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DBoost_NO_BOOST_CMAKE=ON
     - name: Build & Install
       run: cmake --build build --config ${{matrix.buildType}} --target install
+
     # Run test with both bash and powershell and watch for "Using std::cin" on bash but not on powershell
     - name: Test
       working-directory: build
@@ -92,6 +93,20 @@ jobs:
       shell: powershell
       if: runner.os == 'Windows'
       run: ctest --output-on-failure -C ${{matrix.buildType}} --verbose
+    # Run iostream test
+    - name: Manual IOStream test on PowerShell
+      working-directory: build
+      shell: powershell
+      if: runner.os == 'Windows'
+      run: |
+        if ( '${{matrix.standalone}}' -eq 'Standalone' ){ $prefix = "nowide" } else { $prefix = "boost_nowide" }
+        $iostream_exe = "${{matrix.buildType}}/" + $prefix + "-test_iostream.exe"
+        if(!(Test-Path $iostream_exe -PathType Leaf)){ $iostream_exe = "./" + $prefix + "-test_iostream.exe" }
+        # Should show "Using Nowide input/output" and run the tests
+        &$iostream_exe
+        # Will use the std stream bufs due to redirect so should show: "NOT using Nowide input/output"
+        $result = echo "Hello Boost Nowide"| &$iostream_exe passthrough
+        if($result -notcontains "Hello Boost Nowide") { echo "Failed to find output"; exit 1 }
     - name: Test consumption
       working-directory: build
       shell: bash
@@ -179,7 +194,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
-    - uses: DoozyX/clang-format-lint-action@v0.10
+    - uses: DoozyX/clang-format-lint-action@v0.11
       with:
         exclude: './doc'
         clangFormatVersion: 10
